#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
\rm -f constant/solid/polyMesh/allOwner* \
       constant/solid/polyMesh/cell* \
       constant/solid/polyMesh/face* \
       constant/solid/polyMesh/meshModifiers* \
       constant/solid/polyMesh/owner* \
       constant/solid/polyMesh/neighbour* \
       constant/solid/polyMesh/point* \
       constant/solid/polyMesh/edge* \
       constant/solid/polyMesh/zoneToPatchName \
       constant/solid/polyMesh/cellLevel* \
       constant/solid/polyMesh/pointLevel* \
       constant/solid/polyMesh/refinementHistory*, \
       constant/solid/polyMesh/surfaceIndex* \
       constant/solid/cellToRegion \
       *.dat

\rm -rf constant/solid/polyMesh/sets
\rm -rf postProcessing
\rm -rf 0
cp -r save 0
