#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf constant/polyMesh/
mkdir constant/polyMesh

\rm -f *.dat
\rm -f *vtk
\rm -rf postProcessing *.dat
\rm -rf 0
\cp -r save 0
